printWidth: 120
tabWidth: 1
useTabs: true
semi: true
singleQuote: true
quoteProps: as-needed
trailingComma: none
bracketSpacing: true
bracketSameLine: true
arrowParens: always
htmlWhitespaceSensitivity: css
singleAttributePerLine: true
